version: '3.9'

services:
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ib:
    container_name: ib
    image: zdytch/ib-dockerized
    restart: unless-stopped
    environment:
      - IB_APP=tws
      - IB_MODE=paper
      - IB_USER=ib_user
      - IB_PASSWORD=ib_password
      - VNC_PASSWORD=vnc_password
      - TZ=Europe/Helsinki
    volumes:
      - ./config.ini:/root/ibc/config.ini
    ports:
      - 5900:5900
    labels:
      autoheal: "true"
    healthcheck:
      interval: 15s
      timeout: 5s
      retries: 4
